import { useState } from "react";
import { useFilters } from "../utils/FilterContext";
import { getInsights, getProblems, getNotes } from "../utils/selectors";
import { SectionHeader, Card, EmptyState } from "../components/dashboard/Primitives";
import { InsightCard } from "../components/insights/InsightCard";
import { ProblemCard } from "../components/insights/ProblemCard";
import type { NoteCategory } from "../types/dashboard";

const NOTE_COLORS: Record<NoteCategory, string> = {Creative:"bg-signal-coral/10 text-signal-coral",Content:"bg-mint-100 text-mint-700",Platform:"bg-signal-blue/10 text-signal-blue",Campaign:"bg-signal-amber/15 text-signal-amber",Management:"bg-navy-900/8 text-navy-700"};
export default function Insights(){const{month}=useFilters();const[showAllMonths,setShowAllMonths]=useState(false);const insights=getInsights(showAllMonths?undefined:month);const problems=getProblems(showAllMonths?undefined:month);const notes=getNotes(showAllMonths?undefined:month);return <div className="space-y-10"><SectionHeader eyebrow="Intelligence" title="Insight Engine" description="Observation, data, interpretation, hypothesis, and action — kept distinct so a guess is never mistaken for a fact." action={<button onClick={()=>setShowAllMonths((s)=>!s)} className="text-xs font-semibold px-3.5 py-1.5 rounded-full bg-warm-100 text-fog-600 hover:bg-warm-200">{showAllMonths?"This month only":"All months"}</button>}/>{insights.length===0?<EmptyState message="No insights recorded for this selection."/>:<div className="grid grid-cols-1 lg:grid-cols-2 gap-5">{insights.map((i)=><InsightCard key={i.id} insight={i}/>)}</div>}<section><SectionHeader eyebrow="Problems" title="Problem Detection" description="Patterns worth flagging before they compound."/>{problems.length===0?<EmptyState message="No problems detected for this selection."/>:<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{problems.map((p)=><ProblemCard key={p.id} problem={p}/>)}</div>}</section><section><SectionHeader eyebrow="Team" title="Notes & Marketing Intelligence" description="Structured notes from the team, read directly from the data source."/>{notes.length===0?<EmptyState message="No notes recorded for this selection."/>:<Card><div className="space-y-3">{notes.map((n)=><div key={n.id} className="flex gap-3 pb-3 border-b border-navy-900/5 last:border-0 last:pb-0"><span className={`text-[10px] font-semibold uppercase tracking-wide px-2 py-1 rounded-full h-fit shrink-0 ${NOTE_COLORS[n.category]}`}>{n.category}</span><div><p className="text-sm text-navy-800">{n.text}</p><p className="text-fog-400 text-[11px] mt-1">{n.author} · {n.date}</p></div></div>)}</div></Card>}</section></div>}
